name: Build Nebuli/master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
      NEBULIREFERENCES: ${{ github.workspace }}/References
      PROJECT_FOLDER: Nebuli
      Solution_Name: Nebuli.sln
      Project_Path: Nebuli/Nebuli.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Get Nebuli references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:NEBULI_DOWNLOAD_URL -OutFile "$env:NEBULIREFERENCES.zip"
          Expand-Archive -Path "$env:NEBULIREFERENCES.zip" -DestinationPath $env:NEBULIREFERENCES

      - name: List Contents of NebuliReferences folder
        run: |
          Get-ChildItem -Path $env:NEBULIREFERENCES -Recurse

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build Nebuli
        run: |
          $dllPath = Join-Path $env:NEBULIREFERENCES 'References'
          dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} -r $dllPath --no-restore
