name: Build Nebuli/master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
      NEBULIREFERENCES: D:\a\Nebuli\Nebuli\References\References
      PROJECT_FOLDER: Nebuli
      Solution_Name: Nebuli.sln
      Project_Path: Nebuli/Nebuli.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.306'

    # Fetch the required Nebuli references
    - name: Get Nebuli references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri $env:NEBULI_DOWNLOAD_URL -OutFile "$env:NEBULIREFERENCES.zip"
        Expand-Archive -Path "$env:NEBULIREFERENCES.zip" -DestinationPath $env:NEBULIREFERENCES

    # List contents of the NebuliReferences folder (optional, for verification)
    - name: List Contents of NebuliReferences folder
      run: |
        Get-ChildItem -Path $env:NEBULIREFERENCES -Recurse

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}
      
    # List paths that the dependencies are looking for
    - name: List Dependency Paths
      run: |
        dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-restore --dry-run | Select-String -Pattern "Could not resolve this reference|Reference Include"

    # Build the Nebuli project for the specified configuration
    - name: Build Nebuli
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} -r ${{ env.NEBULIREFERENCES }} --no-restore
