name: Nebuli Nuget

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Extract ExternalLibs
        run: |
          Expand-Archive -Path "${{ github.workspace }}\Nebuli\ExternalLibs\dev.zip" -DestinationPath "${{ github.workspace }}\ExternalLibs"
          # Move the DLLs from the "dev" subfolder to the parent folder
          Move-Item -Path "${{ github.workspace }}\ExternalLibs\dev\*" -Destination "${{ github.workspace }}\ExternalLibs"
          # Remove the now empty "dev" subfolder
          Remove-Item -Path "${{ github.workspace }}\ExternalLibs\dev" -Force

      - name: Build Project
        run: dotnet build Nebuli\Nebuli.csproj -c Release

      - name: Pack NuGet
        run: nuget pack Nebuli\Nebuli.csproj -Prop Configuration=Release -IncludeReferencedProjects
