name: publish
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build and Pack NuGet
        run: >
          ./build.ps1 -BuildNuGet

          $File = (Get-ChildItem -Path . -Include 'Nebuli.*.nupkg' -Recurse).Name

          Out-File -FilePath package.txt -InputObject "PackageFile=$File" -Encoding utf-8 -Append
      - name: Publish NuGet Package
        run: nuget push $(Get-Content package.txt | Select-String -Pattern
          '^PackageFile=' | ForEach-Object { $_.ToString().Split('=')[1] })
          -ApiKey ${{ secrets.NUGET_API_KEY }} -Source
          https://api.nuget.org/v3/index.json
