name: Build Nebuli/master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
      NEBULI_REFERENCES_PATH: ${{ github.workspace }}/References
      PROJECT_FOLDER: Nebuli
      Solution_Name: Nebuli.sln
      Project_Path: Nebuli/Nebuli.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    # Fetch the required Nebuli references
    - name: Get Nebuli references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri $env:NEBULI_DOWNLOAD_URL -OutFile "$env:NEBULI_REFERENCES_PATH.zip"
        Expand-Archive -Path "$env:NEBULI_REFERENCES_PATH.zip" -DestinationPath $env:NEBULI_REFERENCES_PATH

    # List contents of the NebuliReferences folder (optional, for verification)
    - name: List Contents of NebuliReferences folder
      run: |
        Get-ChildItem -Path $env:NEBULI_REFERENCES_PATH -Recurse

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the Nebuli project for the specified configuration
    - name: Build Nebuli
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} -r $env:NEBULI_REFERENCES_PATH --no-restore
