name: Nebuli

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
  NEBULI_REFERENCES_PATH: ${{ github.workspace }}/NebuliReferences

jobs:
  push:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      
    - name: Install NuGet
      run: |
        $nuget_loc = "$env:ProgramFiles\NuGet\NuGet.exe"
        $nuget_uri = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
        if (-Not (Test-Path $nuget_loc)) {
          Write-Host "NuGet not found at $nuget_loc. Trying default location..."
          $nuget_loc = "C:\NuGet\NuGet.exe"
          New-Item -ItemType Directory -Force -Path "C:\NuGet"
        }
        if (-Not (Test-Path $nuget_loc)) {
          Write-Host "NuGet not found. Downloading..."
          Invoke-WebRequest -Uri $nuget_uri -OutFile $nuget_loc
          Write-Host "Installed NuGet at $nuget_loc"
        } else {
          Write-Host "Using NuGet from $nuget_loc"
        }

    - uses: actions/checkout@v2.3.4

    - name: Get Nebuli references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.NEBULI_DOWNLOAD_URL }} -OutFile ${{ github.workspace }}/NebuliReferences.zip
        Expand-Archive -Path NebuliReferences.zip -DestinationPath ${{ env.NEBULI_REFERENCES_PATH }}

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build Nebuli
      run: dotnet build --configuration Release --no-dependencies
      
    - name: Navigate to Nebuli directory
      run: cd Nebuli

    - name: Build and Pack NuGet
      run: nuget pack Nebuli\Nebuli.csproj -Prop Configuration=Release -IncludeReferencedProjects


    - name: Push NuGet
      shell: pwsh
      run: nuget push ${{ env.PackageFile }} -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
