name: Nebuli Nuget

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  GDRIVE_FOLDER_URL: https://drive.google.com/drive/folders/19qoFkGeaAHmWfn_G7XCTvx5EhvjKfqE9?usp=sharing
  EXTERNAL_LIBS_DIR: external_libs

jobs:
  push:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Download and Extract External References
      run: |
        mkdir ${{ env.EXTERNAL_LIBS_DIR }}
        curl -L "${{ env.GDRIVE_FOLDER_URL }}/dev.zip" -o ${{ env.EXTERNAL_LIBS_DIR }}/dependencies.zip
        Expand-Archive -Path ${{ env.EXTERNAL_LIBS_DIR }}/dependencies.zip -DestinationPath ${{ env.EXTERNAL_LIBS_DIR }}
      shell: pwsh

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build and Pack NuGet
      run: nuget pack -Prop Configuration=Release -IncludeReferencedProjects
