name: Build and Publish Nebuli Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Manually trigger the workflow from the GitHub Actions UI

jobs:
  build_and_publish:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
      NEBULIREFERENCES: D:\a\Nebuli\Nebuli\References
      PROJECT_FOLDER: Nebuli
      Solution_Name: Nebuli.sln
      Solution_Path: D:\a\Nebuli\Nebuli\Nebuli\Nebuli.sln
      Project_Path: Nebuli/Nebuli.csproj
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Set your NuGet API key as a secret in your repository

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.306'

    # Fetch the required Nebuli references
    - name: Get Nebuli references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri $env:NEBULI_DOWNLOAD_URL -OutFile "$env:NEBULIREFERENCES.zip"
        Expand-Archive -Path "$env:NEBULIREFERENCES.zip" -DestinationPath $env:NEBULIREFERENCES

    # List contents of the NebuliReferences folder (optional, for verification)
    - name: List Contents of NebuliReferences folder
      run: |
        Get-ChildItem -Path $env:NEBULIREFERENCES -Recurse

    # Download and setup NuGet
    - name: Download and Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild ${{ env.Solution_Path }} /t:Restore /p:Configuration=${{ env.configuration }}

    # Build the Nebuli project for the specified configuration
    - name: Build Nebuli
      run: msbuild ${{ env.Project_Path }}/Nebuli.sln --configuration ${{ matrix.configuration }} -r ${{ env.NEBULIREFERENCES }} --no-restore

    # Publish the package to NuGet
    - name: Publish NuGet Package
      run: |
        dotnet nuget push ${{ env.PROJECT_FOLDER }}/bin/${{ matrix.configuration }}/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "${{ env.NUGET_API_KEY }}"
