name: Nebuli

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
  NEBULIREFERENCES: D:\a\Nebuli\Nebuli\NebuliReferences

jobs:
  push:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - uses: actions/checkout@v2.3.4

    - name: Get Nebuli references
      shell: pwsh
      run: |
        echo "Nebuli References Path: $env:NEBULIREFERENCES"
        Invoke-WebRequest -Uri $env:NEBULI_DOWNLOAD_URL -OutFile "$env:NEBULIREFERENCES.zip"
        Expand-Archive -Path "$env:NEBULIREFERENCES.zip" -DestinationPath "$env:NEBULIREFERENCES"

    - name: List Contents of NebuliReferences folder
      run: |
        Get-ChildItem -Path "$env:NEBULIREFERENCES" -Recurse

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      env: 
       NEBULIREFERENCES: D:\a\Nebuli\Nebuli\NebuliReferences
      run: dotnet build Nebuli/Nebuli.csproj --configuration Release -r $env:NEBULIREFERENCES --no-restore

    - name: Pack NuGet
      run: dotnet pack Nebuli/Nebuli.csproj --configuration Release --output D:\a\Nebuli\Nebuli\NuGetPackages -p:IncludeReferencedProjects=true

    - name: Push NuGet
      shell: pwsh
      run: nuget push ${{ env.PackageFile }} -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
