name: Nebuli

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  NEBULI_DOWNLOAD_URL: https://cdn.cedmod.nl/files/References.zip
  NEBULI_REFERENCES_PATH: ${{ github.workspace }}/NebuliReferences

jobs:
  push:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - uses: actions/checkout@v2.3.4

    - name: Get Nebuli references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.NEBULI_DOWNLOAD_URL }} -OutFile ${{ github.workspace }}/NebuliReferences.zip
        Expand-Archive -Path NebuliReferences.zip -DestinationPath ${{ env.NEBULI_REFERENCES_PATH }}

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Create NuGet Packages directory
      run: mkdir D:\a\Nebuli\Nebuli\NuGetPackages

    - name: Build and Pack NuGet
      env:
        NEBULI_REFERENCES: ${{ env.NEBULI_REFERENCES_PATH }}
      run: |
        cd Nebuli  # Navigate to the 'Nebuli' directory
        dotnet pack Nebuli.csproj --configuration Release --output D:\a\Nebuli\Nebuli\NuGetPackages -p:IncludeReferencedProjects=true
        $File = (Get-ChildItem -Path D:\a\Nebuli\Nebuli\NuGetPackages -Include 'Nebuli.*.nupkg' -Recurse).Name
        Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append

    - name: Push NuGet
      shell: pwsh
      run: nuget push ${{ env.PackageFile }} -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
