name: Nebuli Nuget

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Extract ExternalLibs
      run: |
        Expand-Archive -Path "${{ github.workspace }}\Nebuli\ExternalLibs\dev.zip" -DestinationPath "${{ github.workspace }}\ExternalLibs"
    - name: Build and Pack NuGet
      run: nuget pack Nebuli\Nebuli.csproj -Prop Configuration=Release -IncludeReferencedProjects
