name: Nebuli Nuget

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  NEBULIREFERENCES: ${{ github.workspace }}/ExternalLibs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Create NEBULIREFERENCES directory
        run: mkdir ${{ env.NEBULIREFERENCES }}

      - name: Extract ExternalLibs
        run: Expand-Archive -Path "${{ github.workspace }}/Nebuli/ExternalLibs/dev.zip" -DestinationPath "${{ env.NEBULIREFERENCES }}"

      - name: Build Project
        run: dotnet build Nebuli\Nebuli.csproj -c Release

      - name: Pack NuGet
        run: nuget pack Nebuli\Nebuli.csproj -Prop Configuration=Release -IncludeReferencedProjects
